# Generated by Django 4.2.7 on 2025-10-05 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_room_notification_chatmessage_roomparticipant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='FavoriteRoom',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
