# Generated by Django 4.2.7 on 2025-10-29 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_room_cached_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiRecommendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('desired_time', models.DateTimeField()),
                ('categories', models.JSONField(blank=True, default=list)),
                ('top_results', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='accounts_ai_created_81dae6_idx'), models.Index(fields=['user', 'created_at'], name='accounts_ai_user_id_a80596_idx')],
            },
        ),
    ]
