# Generated by Django 5.2.1 on 2025-11-07 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_room_settlement_created_at_room_settlement_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CHAT', '채팅 메시지'), ('JOIN', '참여'), ('LEAVE', '나가기'), ('DONE', '모집 완료'), ('DELETE', '방 삭제')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='accounts.room'),
        ),
    ]
