# Generated by Django 5.2.1 on 2025-11-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='deleted_room_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
