# Generated by Django 5.2.1 on 2025-11-14 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_notification_deleted_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trust_score',
            field=models.FloatField(default=3.0),
        ),
        migrations.CreateModel(
            name='RoomRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='accounts.room')),
            ],
            options={
                'indexes': [models.Index(fields=['room', 'rater'], name='accounts_ro_room_id_93bdf4_idx'), models.Index(fields=['host'], name='accounts_ro_host_id_4fed62_idx')],
                'unique_together': {('room', 'rater')},
            },
        ),
    ]
