# Generated by Django 4.2.7 on 2025-11-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_recalculate_trust_scores'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomrating',
            unique_together={('room', 'rater', 'host')},
        ),
    ]
